window.TOKYO_DATA = {
  person: {
    name: "Atharva",
    fullName: "Atharva Kanherkar",
    katakana: "アタルヴァ カンヘルカル",
    from: "Bengaluru",
    to: "Tokyo",
    work: "Rimo",
    landing: "2026-10-01",
  },
  excluded: [
    "visa",
    "passport admin",
    "flight",
    "company housing",
    "airport taxi",
    "company arrival cash",
  ],
  phases: [
    {
      id: "access",
      title: "D-25 → D-18 · Make India access-proof",
      window: "6–13 Sep",
      range: [25, 18],
      blurb: "Fix anything that still needs a local branch, an Indian OTP, or a working laptop. Once you are in Tokyo these become expensive.",
      tasks: [
        ["bank-1", "Enable international online / POS / ATM on your primary card and verify limits.", "money", "p0", "D-23", "Do this while a failed card still means a local call or a Bengaluru branch visit."],
        ["bank-2", "Set up a second independent payment card.", "money", "p0", "D-21", "Different bank or network if possible. One failed card should not become a Tokyo emergency."],
        ["bank-3", "Keep your Indian SIM alive for OTPs.", "digital", "p0", "D-23", "Long-validity plan. Confirm incoming SMS and that the number can stay active while you live abroad."],
        ["bank-4", "Prepare the HDFC resident → NRO conversion plan. Do not convert early.", "money", "p0", "D-20", "RBI: when you leave India for employment, resident accounts should be redesignated NRO. Save the current HDFC form, list FDs / demat / SIPs, and know the exact post-landing steps."],
        ["money-5", "Download statements and list every recurring India payment.", "money", "p1", "D-20", "Bank, cards, SIPs, subscriptions, EMI, autopay. Cancel anything that only makes sense in India."],
        ["money-6", "Save a remote-close / remote-service path for every India bank you use.", "money", "p1", "D-19", "People get stuck trying to close or convert accounts from Japan. Screenshot the process while you still have a local number and branch."],
        ["dig-1", "Back up laptop + phone + important repos and files.", "digital", "p0", "D-23", "One encrypted local copy and one cloud copy for anything you cannot lose."],
        ["dig-2", "Export 2FA recovery codes and test account recovery.", "digital", "p0", "D-22", "GitHub, Google, Apple, password manager, banking. Store codes somewhere that is not only your phone."],
        ["dig-3", "Confirm the phone is unlocked and recovery email / number are current.", "digital", "p1", "D-21", "You want a Japanese eSIM or SIM without touching the India number."],
        ["dig-4", "Clean the developer machine before the move.", "digital", "p1", "D-20", "OS updates, disk space, SSH keys, Git credentials, package managers, encrypted backup, spare hardware key if you use one."],
        ["admin-1", "Make one encrypted offline Japan-essentials folder.", "digital", "p1", "D-19", "Personal / KYC / employment / education docs you commonly need, plus emergency contacts. Not passport-admin work — just copies you already have."],
      ],
    },
    {
      id: "buy",
      title: "D-17 → D-12 · Buy only the high-leverage stuff",
      window: "14–19 Sep",
      range: [17, 12],
      blurb: "October in Tokyo is wet and cooling, not winter. Buy the compact kit. Leave bulky Japan-easy things for after you see the room.",
      tasks: [
        ["power-1", "Audit every device label for 100–240V input.", "pack", "p0", "D-17", "Japan is 100V. Tokyo / eastern Japan is 50Hz. Type A outlets. Laptop and phone chargers are usually fine; Indian 220–240V-only heat tools are not."],
        ["power-2", "Buy one compact charging setup.", "pack", "p0", "D-16", "100–240V USB-C charger + Type A compatibility + two cables. Buy the Japanese power strip after arrival at Bic / Yodobashi / Akihabara."],
        ["pack-1", "Build a 10-day capsule wardrobe on the bed.", "pack", "p1", "D-15", "Everyday tees / shirts, jeans / chinos, one hoodie, one light rain layer, one clean office outfit. Pack combinations, not random pieces."],
        ["pack-2", "Lock shoes to three roles.", "pack", "p1", "D-15", "Daily walking, gym, clean smart-casual. Tokyo walking punishes bad shoes more than a missing fourth outfit."],
        ["pack-3", "Pack the gym micro-kit you actually use.", "routine", "p1", "D-14", "3–4 training sets, shaker, straps / belt only if they are weekly, gym shoes. Many Tokyo gyms want indoor shoes and a towel."],
        ["pack-4", "Pack only one month of preferred grooming products.", "pack", "p2", "D-14", "Enough to skip week-one shopping friction. Matsumoto Kiyoshi and Welcia will cover the rest."],
        ["med-1", "Check the Japan import rule for every regular medicine you will carry.", "pack", "p0", "D-17", "MHLW: generally up to 1 month of prescription medicine without import confirmation; OTC / quasi-drugs up to 2 months; controlled drugs are a different process. Sort this now."],
        ["med-2", "Keep medicine in original labeled packaging plus a prescription copy.", "pack", "p1", "D-13", "Useful even when Yunyu Kakunin-sho is not required. Portal: impconf.mhlw.go.jp."],
        ["food-0", "Do a bag sweep for meat, dairy, fresh fruit, plants, and soil.", "pack", "p0", "D-13", "Japan Animal Quarantine / Plant Protection: most meat and many fresh plants from India are banned, even packaged souvenirs. When unsure, leave it."],
        ["guitar-1", "If the guitar is coming, make a tiny guitar kit.", "routine", "p2", "D-13", "Picks, capo, tuner, spare strings, cable if relevant. Photograph the serial number and sync tabs."],
        ["gift-1", "Buy a small batch of shelf-stable India gifts.", "people", "p2", "D-12", "Individually wrapped tea / chocolate / snacks. Omiyage, not cargo. No homemade food, no meat, no fresh sweets."],
      ],
    },
    {
      id: "os",
      title: "D-11 → D-7 · Install the Tokyo operating system",
      window: "20–24 Sep",
      range: [11, 7],
      blurb: "October is Tokyo's wettest month. Install alerts, transit, phrases, and food defaults before the last India week eats the calendar.",
      tasks: [
        ["app-1", "Install Safety tips and Disaster Preparedness Tokyo.", "japan", "p0", "D-11", "JNTO Safety tips: earthquake, tsunami, and weather warnings in English. Early October is still typhoon season."],
        ["app-2", "Install / update Google Maps, Google Translate, and Japan Travel or NAVITIME.", "japan", "p1", "D-11", "Download Japanese language pack and offline Tokyo maps."],
        ["app-3", "Add a Tokyo clock and Tokyo weather to the phone.", "digital", "p2", "D-11", "Start thinking in JST. India is 3.5 hours behind Tokyo."],
        ["suica-1", "Save the Suica setup path and try it once.", "japan", "p1", "D-10", "Apple: Wallet → Transit Card → Suica / PASMO. If issuance or top-up is blocked from India, finish it on airport Wi-Fi. Foreign Visa cards fail more often than Mastercard / Amex."],
        ["sim-1", "Shortlist a Japanese mobile plan. Do not over-optimize it now.", "japan", "p1", "D-10", "Resident plans (ahamo, LINEMO, povo, Rakuten) want a residence card and address. Landing-week data can be a travel eSIM; the real Japanese number waits until documents exist."],
        ["jp-1", "Make a 100-phrase survival deck.", "japan", "p1", "D-11", "Station, restaurant, konbini, gym, phone shop, delivery, directions, 'please say that again', 'can I pay by card?'."],
        ["jp-2", "Practice a 45-second self-introduction in Japanese.", "japan", "p1", "D-9", "Name, India, software engineer, just moved to Tokyo, gym / guitar / coffee. You will use this repeatedly."],
        ["jp-3", "Practice writing and reading your name in katakana.", "japan", "p1", "D-9", "アタルヴァ カンヘルカル. Forms get easier when this is automatic."],
        ["food-1", "Write five default high-protein Tokyo meals.", "routine", "p1", "D-8", "One breakfast, one supermarket dinner, two konbini fallbacks, one easy cooked meal. Do not pack a suitcase of protein."],
        ["safe-1", "Memorize 110 and 119. Make an ICE contact card.", "japan", "p0", "D-8", "110 = police. 119 = ambulance / fire. India emergency contact + Japan work contact in the phone and on paper."],
      ],
    },
    {
      id: "close",
      title: "D-6 → D-3 · Finish India properly",
      window: "25–28 Sep",
      range: [6, 3],
      blurb: "Protect the last Bengaluru days from random errands. People and closure first.",
      tasks: [
        ["people-1", "Choose the people you actually want to see before leaving.", "people", "p0", "D-6", "Do not let the last week become 14 guilt-meetings. Pick the few that matter and schedule them."],
        ["people-2", "Do one intentional family meal or day.", "people", "p1", "D-5", "Quality over duration. This will matter more than another packing evening."],
        ["people-3", "Do one final Bengaluru routine you genuinely like.", "people", "p2", "D-5", "Gym, coffee, walk, dinner — something that feels like your life here."],
        ["people-4", "Call or meet the friends you do not want distance to erase.", "people", "p1", "D-4", "Set a sustainable channel now: occasional call, memes, music, whatever you will actually keep."],
        ["home-1", "Leave India stuff findable.", "pack", "p1", "D-4", "Keys, documents, old devices, valuables: label where they are so nobody excavates your room over video call."],
        ["sub-1", "Pause or cancel location-bound memberships.", "money", "p2", "D-3", "Gym, local deliveries, services, subscriptions that only make sense in India."],
      ],
    },
    {
      id: "land",
      title: "D-2 → D-0 · Land calm, not optimized",
      window: "29 Sep–1 Oct",
      range: [2, 0],
      blurb: "The goal is not a perfect suitcase. The goal is arriving on 1 October with sleep, devices, and a 72-hour kit.",
      tasks: [
        ["last-1", "Create a 72-hour personal landing kit.", "pack", "p0", "D-2", "One change of clothes, daily essentials, chargers, regular medicine, adapter, work-ready basics. Everything you need before you have energy to shop."],
        ["last-2", "Run the final device backup and charge pass.", "digital", "p0", "D-1", "Phone, laptop, power bank, headphones. Confirm password manager and recovery access one last time."],
        ["last-3", "Final bag check for restricted food and medicine.", "pack", "p0", "D-1", "Fresh fruit / vegetables, meat products, soil, and controlled medicines. Japan will confiscate and can fine. When unsure, leave it."],
        ["last-4", "Write the first 7 days in one note.", "routine", "p1", "D-1", "Work, groceries, gym, phone / Suica, Japanese, one café walk, one social plan. Nothing else has to be solved immediately."],
        ["last-5", "Set a hard stop on late-night packing.", "routine", "p1", "D-1", "You land 1 October. Sleep is a deliverable."],
        ["last-6", "Photograph the packed setup and a valuables list.", "pack", "p2", "D-0", "Useful for remembering what you brought and what you left."],
        ["last-7", "Write three rules for month one.", "routine", "p1", "D-0", "Example: job first; gym 4× / week; Japanese 20 min / day; side-project intensity only after the city feels stable."],
      ],
    },
  ],
  mustIds: [
    "bank-1", "bank-3", "dig-1", "dig-2", "power-1", "med-1", "food-0",
    "app-1", "safe-1", "people-1", "last-1", "last-2", "last-3",
  ],
  buy: {
    india: [
      "USB-C charger that explicitly says 100–240V, plus a Type A adapter if your plug is not already US/JP shape.",
      "Two good cables, compact power bank, USB-C hub / SSD if they are weekly tools.",
      "Walking shoes, gym shoes, one clean smart-casual pair.",
      "One month of familiar grooming items — not six.",
      "Small shelf-stable India gifts. Individually wrapped.",
      "Shaker and the fitness accessories you actually use.",
      "Light rain layer. October is Tokyo's wettest month (JMA normal 234.8 mm).",
    ],
    tokyo: [
      "Japanese power strip / extension board (Bic, Yodobashi, Akihabara).",
      "A proper umbrella and bulky rainy-day items.",
      "Winter coat later, after you feel late autumn. October mean is 18.0°C, not January.",
      "Household stuff after you see exactly what company housing contains.",
      "Long-term Japanese SIM / eSIM after residence card and address exist.",
      "Protein and food staples after you know the supermarket and gym.",
    ],
    skip: [
      "Indian 220–240V-only hair dryers, kettles, or high-wattage appliances.",
      "Huge protein tubs, months of snacks, random kitchen gear.",
      "A giant winter wardrobe for a 1 October landing.",
      "Storage boxes, hangers, bedding, furniture before seeing the room.",
      "Maybe-useful cables and old gadgets.",
      "Fresh fruit, meat, homemade food, soil on shoes, plants.",
      "Your entire India life. Bring the version you use weekly.",
    ],
  },
  rules: [
    { n: "01", k: "BODY", t: "Train, don't prove anything", d: "4 solid gym sessions a week for the first two weeks. No PR chase while sleep, walking volume, and food are changing." },
    { n: "02", k: "JAPANESE", t: "20 minutes every day", d: "Tiny streak: one listening block + one real-world phrase you can use that day. Living here does not make you fluent." },
    { n: "03", k: "LIFE", t: "Keep the café walk", d: "One solo coffee and a long walk each weekend. Ordinary ritual is how a city starts feeling like yours." },
    { n: "04", k: "WORK", t: "Don't stack every ambition", d: "The new job and city get first claim. Keep side research / startup work light for the first 7–10 days." },
    { n: "05", k: "PEOPLE", t: "One social plan a week", d: "Say yes to small dinners, walks, coworker plans. You do not need a giant calendar to build a life." },
    { n: "06", k: "RESET", t: "Sunday reset", d: "Laundry, room, groceries, calls home, week plan, guitar. Boring on purpose. Stable systems beat chaotic motivation." },
  ],
  sources: [
    { t: "Japan MHLW — medicines", u: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iyakuhin/kojinyunyu/topics/tp010401-1_00001.html", s: "Up to 1 month of prescription medicine is generally within the no-import-confirmation quantity. Larger amounts and controlled drugs need advance procedures. Apply at impconf.mhlw.go.jp." },
    { t: "JNTO — electricity", u: "https://www.japan.travel/en/plan/plug-and-electricity/", s: "Japan uses 100V nationwide. Tokyo / eastern Japan is 50Hz. Standard outlets are Type A. Buy converters in Akihabara, Bic, or Yodobashi." },
    { t: "JMA — Tokyo climate normals 1991–2020", u: "https://www.data.jma.go.jp/stats/en/normal/normal.html", s: "Tokyo mean: 23.3°C and 224.9 mm in September; 18.0°C and 234.8 mm in October. October is the wettest month." },
    { t: "JNTO — Safety tips app", u: "https://www.jnto.go.jp/safety-tips/eng/app.html", s: "Push alerts for earthquakes, tsunami, and weather warnings, with English and many other languages." },
    { t: "Apple — transit cards in Wallet", u: "https://support.apple.com/en-asia/108772", s: "Suica, PASMO, ICOCA, TOICA can be added in Wallet. Express Mode taps gates without unlocking. Updated 25 Mar 2026." },
    { t: "RBI — resident → non-resident accounts", u: "https://www.rbi.org.in/CommonPerson/english/scripts/Notification.aspx?Id=847", s: "Leaving India for employment: existing accounts should be designated NRO. Do not blindly convert before your status actually changes." },
    { t: "HDFC — resident to NRO process", u: "https://www.hdfc.bank.in/nri-banking/resident-to-nro-conversion-process", s: "Conversion form, PAN, passport, visa, overseas address. International debit card is typically hotlisted and replaced." },
    { t: "MAFF Animal Quarantine — food", u: "https://www.maff.go.jp/aqs/english/product/import.html", s: "Most meat and animal products cannot enter Japan without a government inspection certificate — including souvenirs and packaged food. Penalties are severe." },
  ],
  pulse: [
    { k: "Konbini physics", s: "X / Tokyo Signal", d: "Separate hot and cold items before you walk. Condensation and heat make a 12-minute walk annoying." },
    { k: "Fluency myth", s: "X / long-term residents", d: "Moving to Japan does not make you fluent. People live here 20 years on survival sentences. Keep the 20-minute streak." },
    { k: "First-month burn", s: "X / India→Japan anecdote", d: "One Indian mover publicly logged ~₹90k in 25 days for rent, utilities, Wi-Fi, SIM, transport — excluding food. Your company housing changes the number; the shock pattern is real. Budget a buffer." },
    { k: "Suica before the gate", s: "X + Apple Support", d: "Add Suica to Apple Wallet if the card goes through. If India issuance fails, airport Wi-Fi is the fallback — not a ticket-machine panic." },
    { k: "Typhoon month", s: "X news + JMA", d: "Early September 2026 still had typhoon talk aimed at southern Japan. Landing 1 October: rain and wind are normal. Install Safety tips." },
    { k: "India banking from abroad", s: "X / customer reports", d: "People get stuck closing or converting Indian accounts after they leave. Screenshot every remote path while you are still here." },
    { k: "Cash still exists", s: "X / regional Japan", d: "Tokyo cards and IC work almost everywhere. Small shops and trips outside the core still want cash. Keep a thin yen float after arrival." },
  ],
  phrases: [
    { jp: "はじめまして。アタルヴァです。", romaji: "Hajimemashite. Ataruva desu.", en: "Nice to meet you. I'm Atharva." },
    { jp: "インドから来ました。エンジニアです。", romaji: "Indo kara kimashita. Enjinia desu.", en: "I came from India. I'm an engineer." },
    { jp: "東京に引っ越したばかりです。", romaji: "Tōkyō ni hikkoshita bakari desu.", en: "I just moved to Tokyo." },
    { jp: "もう一度お願いします。", romaji: "Mō ichido onegai shimasu.", en: "One more time, please." },
    { jp: "ゆっくり話してください。", romaji: "Yukkuri hanashite kudasai.", en: "Please speak slowly." },
    { jp: "英語でお願いします。", romaji: "Eigo de onegai shimasu.", en: "English, please." },
    { jp: "カードで払えますか。", romaji: "Kādo de haraemasu ka.", en: "Can I pay by card?" },
    { jp: "すみません、これは何ですか。", romaji: "Sumimasen, kore wa nan desu ka.", en: "Excuse me, what is this?" },
    { jp: "これをください。", romaji: "Kore o kudasai.", en: "This one, please." },
    { jp: "袋はいりません。", romaji: "Fukuro wa irimasen.", en: "I don't need a bag." },
    { jp: "この電車は新宿に行きますか。", romaji: "Kono densha wa Shinjuku ni ikimasu ka.", en: "Does this train go to Shinjuku?" },
    { jp: "次はどこですか。", romaji: "Tsugi wa doko desu ka.", en: "What is the next stop?" },
    { jp: "乗換はどこですか。", romaji: "Norikae wa doko desu ka.", en: "Where is the transfer?" },
    { jp: "Suicaで払います。", romaji: "Suica de haraimasu.", en: "I'll pay with Suica." },
    { jp: "ジムの見学をお願いします。", romaji: "Jimu no kengaku o onegai shimasu.", en: "I'd like to look around the gym." },
    { jp: "タオルはありますか。", romaji: "Tauru wa arimasu ka.", en: "Do you have towels?" },
    { jp: "辛くしないでください。", romaji: "Karaku shinaide kudasai.", en: "Please don't make it spicy." },
    { jp: "ビーガンではありません。肉は大丈夫です。", romaji: "Bīgan dewa arimasen. Niku wa daijōbu desu.", en: "I'm not vegan. Meat is fine." },
    { jp: "アレルギーはありません。", romaji: "Arerugī wa arimasen.", en: "I have no allergies." },
    { jp: "高タンパク質の食べ物はどこですか。", romaji: "Kō tanpakushitsu no tabemono wa doko desu ka.", en: "Where is the high-protein food?" },
    { jp: "配達をお願いします。", romaji: "Haitatsu o onegai shimasu.", en: "Delivery, please." },
    { jp: "住所はこれから登録します。", romaji: "Jūsho wa kore kara tōroku shimasu.", en: "I will register my address soon." },
    { jp: "在留カードはこれです。", romaji: "Zairyū kādo wa kore desu.", en: "This is my residence card." },
    { jp: "調子が悪いです。", romaji: "Chōshi ga warui desu.", en: "I don't feel well." },
    { jp: "助けてください。", romaji: "Tasukete kudasai.", en: "Please help me." },
  ],
  meals: [
    { t: "Breakfast", d: "Lawson / 7-Eleven Greek-style yogurt or protein pudding + banana + canned coffee. Or eggs and natto rice if the kitchen exists." },
    { t: "Supermarket dinner", d: "Chicken breast or salmon from Gyomu / Life / OK Store, frozen veg, rice. Simple, repeatable, high protein." },
    { t: "Konbini A", d: "Salad chicken + boiled eggs + onigiri. Separate hot and cold bags before you walk." },
    { t: "Konbini B", d: "Grilled fish teishoku-style box or tofu + edamame + milk. Not a suitcase of whey." },
    { t: "Cooked reset", d: "One pan: chicken, cabbage, soy, sesame, rice. Sunday reset meal. Learn this once." },
  ],
  sims: [
    { t: "Week one", d: "Travel eSIM for data if you need maps immediately. Keep the India number alive for OTPs." },
    { t: "Resident plan", d: "ahamo / LINEMO / povo / Rakuten usually want a residence card and a registered address. Shortlist now, sign later." },
    { t: "English-easier", d: "Rakuten and some foreigner-focused shops are less painful in English. ahamo / LINEMO are often Japanese-first." },
    { t: "Number", d: "A real Japanese number waits until documents exist. Do not treat this as a 1 October blocker." },
  ],
  emergencies: [
    { n: "110", t: "Police" },
    { n: "119", t: "Ambulance / fire" },
    { n: "118", t: "Coast guard" },
  ],
  climate: [
    { m: "Sep", temp: "23.3°C", rain: "224.9 mm", note: "Late summer, still humid." },
    { m: "Oct", temp: "18.0°C", rain: "234.8 mm", note: "Wettest month. Light layers + rain." },
    { m: "Nov", temp: "12.5°C", rain: "96.3 mm", note: "Buy real layers after you feel it." },
  ],
};
